### ISSUE TITLE
Common interfaces

### ISSUE THREAD

**Issue by rikonor** [alanctgardner/gogen-avro#17]
Hey Alan,

I would like to discuss something with you.

It's come up that the generated code contains some things that could be better represented as interfaces. Specifically, the following two:

```go
type Serializable interface {
	Serialize(w io.Writer) error
}
```

```go
type Writer interface {
	WriteRecord(v Serializable) error
	Flush() error
}
```

Internally, for us, it made a lot of sense to define those interfaces in another package (`avroutil`) and make some changes to the generated code that allow us to treat some of the functions more generically. Examples:

Changing the function signature of Deserialize to:
```go
func(r io.Reader) (avroutil.Serializable, error)
```

Changing the function signature of NewContainerWriter to:
```go
func(writer io.Writer, codec string, recordsPerBlock int64) (avroutil.Writer, error)
```

Allows us to treat the generated Deserialize and NewContainerWriter functions as having the same type (which lets you pass them around, etc).

I believe this might be beneficial to `gogen-avro` in general but it would require defining those interfaces somewhere and the generated code trying to import them, which I'm not sure if you would be interested in doing or not.

**Comment by alanctgardner** [comment]
I think I understand the use case - basically we could pull all of the container writing logic out into a separate package, and have all the record definitions implement the Serializable interface?

I see some difficulties with this:
- the container writer needs to know the schema of the records, in order to write the header
- the container writer needs to enforce that all the records in the container are actually of the same type

This is why right now we generate a different ContainerWriter with a unique signature for `WriteRecord()` for each different record type. 

The alternative would be something like:

``` golang
type Serializable interface {
	Serialize(io.Writer) error
	Schema() string
}
```

``` golang
type Writer interface {
	WriteRecord(v Serializable) error
	Flush() error
}
```

`NewContainerWriter` could have the suggested signature, and it would have to lazily write the header when it sees the first record, then check that the schemas are equal for every subsequent record.

I think `Deserialize` is still OK the way it is, it's always possible to upcast from the specific generated type to `avroutil.Serializable`. 

Does that sound good? I've got some other stuff in the pipeline but it would make my life easier to rewrite the container support so there's no generated container code.

**Comment by rikonor** [comment]
Hey Alan,

Looks great! I'll make some time over the weekend to try it out. Thanks for taking the time to make these changes.

**Comment by rikonor** [comment]
Tested and works great! Thank you so much for taking the time. Avro is much less painful to work with thanks to this library.

I suspect we still have to run a slight fork with Deserialize returning an `AvroRecord` - we have a piece of code with a struct containing:
```
DeserializeFn func(r io.Reader) (AvroRecord, error)
```
So that allows us to have a slice of those structs, each with a different `Deserialize` function.
